"""
gitignore_inject.py - Safe inject/remove of an agent-system block in .gitignore.

The block is delimited by sentinel comments so it can be found and updated idempotently.
Running inject twice is safe — the block is replaced, not duplicated.
"""
from __future__ import annotations

from pathlib import Path

BLOCK_START = "# --- agent-system --- DO NOT EDIT THIS BLOCK MANUALLY ---"
BLOCK_END = "# --- end agent-system ---"

# Files/patterns that should be IGNORED in the target workspace (not committed).
# These are agent-system internals that don't belong in any project's git.
IGNORE_PATTERNS = [
    "# Agent-system machine-local config (not portable between machines)",
    ".vscode/agent-system.json",
    "AGENT.md",   # contains absolute paths — regenerated by install.py
    "# Agent runtime artifacts (stored in ~/.agent-system, not the project)",
    "agent_artifacts/",
    ".agent-state/",
    "# Temporary agent-generated scratch files",
    "*_agent_report.md",
    "*_agent_analysis.txt",
    "*_agent_summary.md",
    "*_ai_analysis.txt",
    "agent_*.txt",
    "agent_*.md",
    "debug_*.txt",
    "debug_*.md",
]

# Files that should NOT be in the ignore block because they belong to the
# target workspace's git: CHANGELOG.md, CHANGELOG.json, reporting/data/,
# RELEASE_NOTES.md, .vscode/tasks.json, .vscode/settings.json


def _build_block() -> str:
    lines = [BLOCK_START] + IGNORE_PATTERNS + [BLOCK_END]
    return "\n".join(lines)


def inject_gitignore(workspace: Path) -> bool:
    """Add or update the agent-system block in workspace/.gitignore.

    Returns True if a change was made, False if already up to date.
    """
    gitignore = workspace / ".gitignore"
    block = _build_block()

    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""

    # Remove old block if present (for idempotent update)
    cleaned = _strip_block(existing)

    new_content = cleaned.rstrip("\n") + "\n\n" + block + "\n"

    if new_content == existing:
        return False

    gitignore.write_text(new_content, encoding="utf-8")
    return True


def remove_gitignore(workspace: Path) -> bool:
    """Remove the agent-system block from workspace/.gitignore.

    Returns True if the block was found and removed.
    """
    gitignore = workspace / ".gitignore"
    if not gitignore.exists():
        return False
    existing = gitignore.read_text(encoding="utf-8")
    cleaned = _strip_block(existing)
    if cleaned == existing:
        return False
    gitignore.write_text(cleaned.rstrip("\n") + "\n", encoding="utf-8")
    return True


def _strip_block(content: str) -> str:
    """Return content with the agent-system block removed."""
    lines = content.splitlines(keepends=True)
    result: list[str] = []
    inside = False
    for line in lines:
        stripped = line.rstrip("\n")
        if stripped == BLOCK_START:
            inside = True
            continue
        if stripped == BLOCK_END:
            inside = False
            continue
        if not inside:
            result.append(line)
    return "".join(result)


if __name__ == "__main__":
    import argparse, sys
    p = argparse.ArgumentParser()
    p.add_argument("action", choices=["inject", "remove"])
    p.add_argument("workspace", type=Path)
    args = p.parse_args()
    if args.action == "inject":
        changed = inject_gitignore(args.workspace)
        print("Injected block." if changed else "Block already up to date.")
    else:
        changed = remove_gitignore(args.workspace)
        print("Removed block." if changed else "No block found.")
